### ISSUE TITLE
Connection lost, retrying

### ISSUE THREAD

**Issue by jocaplanaltonet** [MS-Jahan/Messenger-Message-Logger#5]
Program Started!

Listening...
Connection lost, retrying
Connection lost, retrying
Connection lost, retrying
Connection lost, retrying
Connection lost, retrying
Connection lost, retrying
Connection lost, retrying
Connection lost, retrying

**Comment by MS-Jahan** [comment]
It is related to [fbchat](https://github.com/fbchat-dev/fbchat), so create an issue there.

By the way, are you using the same account which you use in your smartphone or PC? Have you tried with another account?

**Comment by jocaplanaltonet** [comment]
> It is related to [fbchat](https://github.com/fbchat-dev/fbchat), so create an issue there.
> 
> By the way, are you using the same account which you use in your smartphone or PC? Have you tried with another account?



By the way, are you using the same account which you use in your smartphone or PC?
yes

Have you tried with another account?
Yes

after restarting a few times, normalized, in one of the accounts signaled fraud on the phone and asked to change the password, more ... this is ok.
