### ISSUE TITLE
fbchat._exception.FBchatUserError: Login failed. Check email/password.

### ISSUE THREAD

**Issue by aksuited** [MS-Jahan/Messenger-Message-Logger#7]
Does anyone have a suggestion for me as I have installed all requirements and configured the login info and it is failing to login with verified good credentials I have tried multiple accounts also

python main.py
Logging in facebook@email.com...
Traceback (most recent call last):
  File "C:\Users\user\main.py", line 501, in <module>
    login_logout()
  File "C:\Users\user\main.py", line 57, in login_logout
    client = CustomClient(email, password, max_tries=1)
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\fbchat\_client.py", line 103, in __init__
    self.login(email, password, max_tries, user_agent=user_agent)
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\fbchat\_client.py", line 205, in login
    self._state = State.login(
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\fbchat\_state.py", line 153, in login
    raise _exception.FBchatUserError(
fbchat._exception.FBchatUserError: Login failed. Check email/password. (Failed on url: https://m.facebook.com/login.php?login_attempt=1)

**Comment by msoffice95** [comment]
Did you get it working?

**Comment by SnowbiEz** [comment]
It isn't working for me either. I got the same issue, code not working. PLS FIX!

**Comment by MS-Jahan** [comment]
Sorry, as I'm busy with my work. 

The `fbchat` module is not usable at the moment as Facebook changed their login system or has done something with their security system. It was not working the last time I tried.

I had to make some changes to the `fbchat` version 1, using browser cookies and worked that way. Although it works immediately, it stops working after 2-3 hours and the account gets temporarily blocked.

**Comment by MS-Jahan** [comment]
Use this branch of my `fbchat` fork: https://github.com/ms-jahan/fbchat/tree/v1

Download the zip, extract, and place the fbchat folder (marked in the image) in the same directory of your script.
![image](https://user-images.githubusercontent.com/27774290/161401009-4c8b53e6-aa81-4f0d-a58a-f009ad740d00.png)


If you go to the storage tab in browser developer tools, you'll get the cookies. you can save them in a JSON file (`session.json`) and then read the file in the script as a cookie (This repo's script already does that, you have to save it as `session.json` in the same directory).

![image](https://user-images.githubusercontent.com/27774290/161401057-e947ef54-18c9-4a51-8f9b-2d39c17bc25d.png)

# Edited:
The `session.json` file should look like [this](https://github.com/MS-Jahan/Messenger-Message-Logger/blob/master/sample_session.json).

**Comment by HISHRAQ** [comment]
![image](https://user-images.githubusercontent.com/103412447/167256623-b1851f05-8e65-4946-b487-3dc125e679df.png)
Can you tell me whats wrong with this?

**Comment by sors89** [comment]
> Use this branch of my `fbchat` fork: https://github.com/ms-jahan/fbchat/tree/v1
> 
> Download the zip, extract and place the fbchat folder (marked in the image) in the same directory of your script. ![image](https://user-images.githubusercontent.com/27774290/161401009-4c8b53e6-aa81-4f0d-a58a-f009ad740d00.png)
> 
> If you go to the storage tab in browser developer tools, you'll get the cookies. you can save then in a JSON file (`session.json`) and then read the file in the script as cookie (This repo's script already does that, you have to save it as `session.json` in the same directory). ![image](https://user-images.githubusercontent.com/27774290/161401057-e947ef54-18c9-4a51-8f9b-2d39c17bc25d.png)

What does the `session.json` form look like? I have added the brackets but still not working

**Comment by MS-Jahan** [comment]
@Exodius-GG Hi, I've recently checked the fbchat module and it's not working.

`session.json` is a json file. Something like:

```
{
"c_user": "<value>",
"datr": "<value>",
....<other_values>...
}
```

**Comment by sors89** [comment]
> @Exodius-GG Hi, I've recently checked the fbchat module and it's not working.
> 
> `session.json` is a json file. Something like:
> 
> ```
> {
> "c_user": "<value>",
> "datr": "<value>",
> ....<other_values>...
> }
> ```


I hope there will an be an update from you if the fbchat module gets it working again.

**Comment by MS-Jahan** [comment]
Hi Everyone!

I've fixed the issue of the `fbchat` login module. Anyone know doesn't know, please note that `fbchat` isn't created by me, nor officially maintained by me. So it's not my responsibility to maintain it, but I used to personally. As I'm getting very busy now-a-days, it's really hard to maintain hobby-ish things.


Okay, just follow the instructions written [here](https://github.com/MS-Jahan/Messenger-Message-Logger/issues/7#issuecomment-1086722859). No need to use any `session.json` file. It should be automatically created after successfully logging in.


**EDIT**: The instruction in the [README.md](https://github.com/MS-Jahan/Messenger-Message-Logger/blob/master/README.md) is also valid or the same thing.

**Comment by HISHRAQ** [comment]
> Hi Everyone!
> 
> I've fixed the issue of the `fbchat` login module. Anyone know doesn't know, please note that `fbchat` isn't created by me, nor officially maintained by me. So it's not my responsibility to maintain it, but I used to personally. As I'm getting very busy now-a-days, it's really hard to maintain hobby-ish things.
> 
> Okay, just follow the instructions written [here](https://github.com/MS-Jahan/Messenger-Message-Logger/issues/7#issuecomment-1086722859). No need to use any `session.json` file. It should be automatically created after successfully logging in.
> 
> **EDIT**: The instruction in the [README.md](https://github.com/MS-Jahan/Messenger-Message-Logger/blob/master/README.md) is also valid or the same thing.

Hey MS-JAHAN,
Thanks for the update!
Have you seen this,
https://github.com/telegram-sms/telegram-sms
is it possible to make an app like this?
I have some old android smartphone which I can use to run them 24/7.

**Comment by MS-Jahan** [comment]
> > Hi Everyone!
> > I've fixed the issue of the `fbchat` login module. Anyone know doesn't know, please note that `fbchat` isn't created by me, nor officially maintained by me. So it's not my responsibility to maintain it, but I used to personally. As I'm getting very busy now-a-days, it's really hard to maintain hobby-ish things.
> > Okay, just follow the instructions written [here](https://github.com/MS-Jahan/Messenger-Message-Logger/issues/7#issuecomment-1086722859). No need to use any `session.json` file. It should be automatically created after successfully logging in.
> > **EDIT**: The instruction in the [README.md](https://github.com/MS-Jahan/Messenger-Message-Logger/blob/master/README.md) is also valid or the same thing.
> 
> Hey MS-JAHAN, Thanks for the update! Have you seen this, https://github.com/telegram-sms/telegram-sms is it possible to make an app like this? I have some old android smartphone which I can use to run them 24/7.

Hey, thanks for your query. But I think the Issues section should only be used for discussing issues related to the particular Github repository.

**Comment by Exodius-GG** [comment]
> Hi Everyone!
> 
> I've fixed the issue of the `fbchat` login module. Anyone know doesn't know, please note that `fbchat` isn't created by me, nor officially maintained by me. So it's not my responsibility to maintain it, but I used to personally. As I'm getting very busy now-a-days, it's really hard to maintain hobby-ish things.
> 
> Okay, just follow the instructions written [here](https://github.com/MS-Jahan/Messenger-Message-Logger/issues/7#issuecomment-1086722859). No need to use any `session.json` file. It should be automatically created after successfully logging in.
> 
> **EDIT**: The instruction in the [README.md](https://github.com/MS-Jahan/Messenger-Message-Logger/blob/master/README.md) is also valid or the same thing.

The previous error has been fixed but now im facing with this new error: 
`fbchat._exception.FBchatUserError: Login failed. Check email/password. (Failed on url: https://m.facebook.com/reg/?cid=103&refsrc=deprecated&_rdr)`

**Comment by sors89** [comment]
> Hi Everyone!
> 
> I've fixed the issue of the `fbchat` login module. Anyone know doesn't know, please note that `fbchat` isn't created by me, nor officially maintained by me. So it's not my responsibility to maintain it, but I used to personally. As I'm getting very busy now-a-days, it's really hard to maintain hobby-ish things.
> 
> Okay, just follow the instructions written [here](https://github.com/MS-Jahan/Messenger-Message-Logger/issues/7#issuecomment-1086722859). No need to use any `session.json` file. It should be automatically created after successfully logging in.
> 
> **EDIT**: The instruction in the [README.md](https://github.com/MS-Jahan/Messenger-Message-Logger/blob/master/README.md) is also valid or the same thing.



> Hi Everyone!
> 
> I've fixed the issue of the `fbchat` login module. Anyone know doesn't know, please note that `fbchat` isn't created by me, nor officially maintained by me. So it's not my responsibility to maintain it, but I used to personally. As I'm getting very busy now-a-days, it's really hard to maintain hobby-ish things.
> 
> Okay, just follow the instructions written [here](https://github.com/MS-Jahan/Messenger-Message-Logger/issues/7#issuecomment-1086722859). No need to use any `session.json` file. It should be automatically created after successfully logging in.
> 
> **EDIT**: The instruction in the [README.md](https://github.com/MS-Jahan/Messenger-Message-Logger/blob/master/README.md) is also valid or the same thing.

Getting blocked by facebook over and over again.

**Comment by MS-Jahan** [comment]
@Exodius-GG Yeah, same. When I used it 2 years ago, it took almost 3 days before the account gets temporarily blocked. But now it takes only a few hours.

May need to dig deeper, but currently too busy to fix it.

**Comment by sors89** [comment]
> @Exodius-GG Yeah, same. When I used it 2 years ago, it took almost 3 days before the account gets temporarily blocked. But now it takes only a few hours.
> 
> May need to dig deeper, but currently too busy to fix it.

I was wondering if you still having the login issue. I tried the latest fbchat but still get blocked everytime i run the code

**Comment by rochonastore** [comment]
> I was wondering if you still having the login issue. I tried the latest fbchat but still get blocked everytime i run the code

The last time I replied here, I tried logging in from the script. I think that's why it looked suspicious and that's why facebook temporarily blocked me every time.

I've been using the script for more than 4 days; 24 hours. Sometimes just manually stopped the script and restarted, 2-3 times in a day. It's working fine. This time I copied cookies from a browser (Kiwi Browser, from Android) and used in on Termux. You can try the same.

**Comment by MS-Jahan** [comment]
> I was wondering if you still having the login issue. I tried the latest fbchat but still get blocked everytime i run the code

The last time I replied here, I tried logging in from the script. I think that's why it looked suspicious and that's why facebook temporarily blocked me every time.

I've been using the script for more than 4 days; 24 hours. Sometimes just manually stopped the script and restarted, 2-3 times in a day. It's working fine. This time I copied cookies from a browser (Kiwi Browser, from Android) and used in on Termux. You can try the same.

**Comment by MS-Jahan** [comment]
> @Exodius-GG Hi, I've recently checked the fbchat module and it's not working.
> 
> `session.json` is a json file. Something like:
> 
> ```
> {
> "c_user": "<value>",
> "datr": "<value>",
> ....<other_values>...
> }
> ```

Here is an example of a `session.json` file:
https://github.com/MS-Jahan/Messenger-Message-Logger/blob/master/sample_session.json

**Comment by PawiX25** [comment]
I'm missing the "m_page_voice" cookie, i can't login to the logger anyways.

**Comment by MS-Jahan** [comment]
> I'm missing the "m_page_voice" cookie, i can't login to the logger anyways.

Sorry, the "m_page_voice" cookie is optional. Not compulsory.

Edited the sample json file.

**Comment by akiraaisha** [comment]
Can someone tell me if this has resolved?

**Comment by MS-Jahan** [comment]
> Can someone tell me if this has resolved?

Follow the readme file, this issue, and try it yourself. Eventually, Facebook will soft-block the account now and then, you'll have to keep logging into the account from the browser, change the password and use it again,

I've automated this password-changing step and some months later, that account got blocked and Facebook asked for documents.

The [Beeper](https://www.beeper.com/) App supports messenger. You can get the code of how they implemented Facebook Messenger in their app here: https://github.com/mautrix/facebook
If I had enough time, I would look into the code and try to build a new module instead of using fbchat.

The issue is closed now.
